### ISSUE TITLE
Email address for suggest a resource is incorrect

### ISSUE THREAD

**Issue by The7thGuest** [lm-tools/digital-resource-library#53]
Email address in the link for "Suggest a resource (email)" is currently wrong

<img width="385" alt="screen shot 2017-07-06 at 15 07 14" src="https://user-images.githubusercontent.com/6169924/27915013-d83f2804-625c-11e7-88d3-033497cbcc08.png">

**Comment by jessstubenbord** [comment]
Being taken care of in #51

**Comment by EdLuff** [comment]
New email set up for the tool is = 

digitalresourcelibrary@digital.uc.dwp.gov.uk

**Comment by jessstubenbord** [comment]
fixed in #58
